cache_expiration: 86400
cache_dir: "~/.description_harvester/cache"
last_query: '1745864673'
online_content_label: "Online access"
metadata:
- ssi:
  - date_uploaded
- ssm:
  - date_digitized
  - extent
- ssim:
  - legacy_id
  - resource_type
  - coverage
  - preservation_package
  - creator
  - contributor
  - preservation_format
  - source
- tesm:
  - processing_activity
- tesim:
  - description
solr_core: arclight
solr_url: https://solr.example.com:8984/solr
